version: '3.0'


services:

  influxdb:
    image: influxdb:1.8
    restart: always
    volumes: 
      - ~/influxdb:/var/lib/influxdb
      - ~/influxdb2:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime
    privileged: true
    ports:
      - "31886:8086"
    environment:
      - INFLUXDB_DB=ketidb
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ROOT_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - TZ=Asia/Seoul

  mosquitto:
    restart: always
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 31883:1883

  comm2center:
    restart: unless-stopped
    build:
      context: ./comm2center
      dockerfile: Dockerfile
    depends_on:
      - influxdb
      - mosquitto
    volumes:
      - /etc/localtime:/etc/localtime

  restfulapi:
    build:
      context: ./restfulapi
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "31020:5000"
    volumes: 
      - /etc/localtime:/etc/localtime
      - ./restfulapi/img:/app/img/
